### ISSUE TITLE
theme url pointing to wrong folder path

### ISSUE THREAD

**Issue by giohappy** [mitmel/OpenLocast-Web#2]
I've just finished setting up Locast, but I get errors on the browser because it tries to load nonexistent resources and wrong paths:

"NetworkError: 404 Not Found - http://localhost/locast/static/js/theme/default/style.css"
style.css
"NetworkError: 404 Not Found - http://localhost/locast/static/js/img/north-mini.png"
north-mini.png
"NetworkError: 404 Not Found - http://localhost/locast/static/js/img/west-mini.png"
west-mini.png
"NetworkError: 404 Not Found - http://localhost/locast/static/js/img/east-mini.png"
east-mini.png
"NetworkError: 404 Not Found - http://localhost/locast/static/js/img/zoom-plus-mini.png"
zoom-p...ini.png
"NetworkError: 404 Not Found - http://localhost/locast/static/js/img/slider.png"
slider.png
"NetworkError: 404 Not Found - http://localhost/locast/static/js/img/zoombar.png"
zoombar.png
"NetworkError: 404 Not Found - http://localhost/locast/static/js/img/south-mini.png"
south-mini.png
"NetworkError: 404 Not Found - http://localhost/locast/static/js/img/zoom-minus-mini.png"

**Comment by amarkbo** [comment]
This is actually an issue with the way OpenLayers handles styling. Since OpenLocast doesn't make use of this, the files don't exist (their paths are hardcoded into OpenLayers). It shouldn't affect operation, but perhaps we should provide empty image files / style sheets so this error doesn't pop up.

**Comment by giohappy** [comment]
Ok, I see. Thanks.
