### ISSUE TITLE
Questions on some basic OpenLocast concepts

### ISSUE THREAD

**Issue by giohappy** [mitmel/OpenLocast-Web#3]
I've been able to setup the Django project, but I have some troubles:
- I don't understand what boundries are and how they should be used. I've created a boundry and set it as default, but I cannot find any reference to this object inside the web frontpage...
- I don't understand how itineraries can/should be managed. Are "collections" meant itineraries?

I would be grateful if you could help me in this startup phase, just in case you intend to support the community and mantain the project.
Thanks a lot.

Regards,
Giovanni

**Comment by amarkbo** [comment]
Apologies for the (very) slow response

A default boundry is can use to restrict the location of casts – it won't allow any casts to be posted with coordinates outside the polygon. The default boundry gets displayed on the map. Currently, non-default boundaries don't have any effect.

This is a bit confusing, I know – I will work towards making this feature a bit more robust.

Collections can be used to create itineraries, but they are more generic than that. A collection is simply a collection of casts. An itinerary is basically a collection with a path set, but the path doesn't actually have any effect on casts in a collection, it is just draw on the map. Unfortunately, there is a known issue where the path disappears on a mouse hover.

Thank you for the feedback! We're working hard to maintain the project, but sometimes we don't have as many resources as we'd like.
