### ISSUE TITLE
About the boundatries

### ISSUE THREAD

**Issue by ghost** [mitmel/OpenLocast-Web#36]
I've created a region using the boundaries feature. How do i connect the boundaries to a group of users ? For Instance, I have my Europe Boundary, a group called Investigators Europe, and users in this group. How do i narrow the scope where i user can send a cast ? Am i doing it right, or is there another logic to it?

**Comment by amarkbo** [comment]
The boundaries feature isn't fully fleshed out yet, unfortunately, so there is no way to connect a group to it. There is support for multiple boundaries – however, at this point, only the boundary marked as "default" will have any effect. This will limit all users to post casts within this boundary.
