### ISSUE TITLE
Default map zooming

### ISSUE THREAD

**Issue by mvdandrieux** [mitmel/OpenLocast-Web#41]
Is the map zooming out automatically to display all the casts at a glance? Also, the max dezoom settings do not allow to see enough of the map, hence making quite difficult to browse distant places.

**Comment by mvdandrieux** [comment]
Also, i believe there is no server-side event to automatically refresh the casts. So when we apple R the page to see new casts, the maps brings you back to Paris, no idea why, but it's also disturbing.

**Comment by amarkbo** [comment]
This will be hopefully solved with #16. Also, opened new issue to support a map refresh without a page refresh #53
