### ISSUE TITLE
Casts disappearing

### ISSUE THREAD

**Issue by mvdandrieux** [mitmel/OpenLocast-Web#42]
![there](https://f.cloud.github.com/assets/3766061/275136/da50ec78-907d-11e2-898f-233eb93b2661.png)
![notthere](https://f.cloud.github.com/assets/3766061/275139/e4f03206-907d-11e2-9c15-0663499185a4.png)

A cast i've created used to appear on the map on the front-end (http://mel-prod.media.mit.edu/eranos/admin/traveler/cast/9/), no longer did while more recent casts were here, and after some refresh, re-appeared, or disapeared again (cf there/notthere captures). Any idea ?

**Comment by amarkbo** [comment]
Not sure, will keep an eye out!

**Comment by mvdandrieux** [comment]
This is how you can reproduce the bug : 
1. go to http://mel-prod.media.mit.edu/eranos/ you'll see two casts in paris
2. click on "The future of socialising". It loads and one of the two casts disappears (http://mel-prod.media.mit.edu/eranos/admin/traveler/cast/9/)

**Comment by amarkbo** [comment]
The cast disappears because it is not part of the collection "The future of socialising" 

The cast is not part of any collection, so the only way to see it is in the "all casts" view.

**Comment by mvdandrieux** [comment]
That's what i just found out. Got it. thanks!
