### ISSUE TITLE
Image resize / upload

### ISSUE THREAD

**Issue by mvdandrieux** [mitmel/OpenLocast-Web#45]
So, when we try to upload a picture trough the upload media feature, if the image comes from, say, an iPhone 4, and weights around 2mo, it doesn't work. Is it a server side setting (post max size or max upload) or a locast limitation ? Could we pump up the limit a bit ? Or upload big images and resize them afterwards ?

My concern if to block as rarely as possible a user trying to upload data.

Personal experience : since no max image size is given, i've had to scale down my iphone pictures 6 times before i found the right size...

**Comment by amarkbo** [comment]
max_upload_size is a setting that currently only limits uploads from the front end. However, we want this to limit API uploads as well. See issue #18, and I've opened another issue to make sure this setting is shown on the front end #52
