### ISSUE TITLE
Inconsistent time zone

### ISSUE THREAD

**Issue by mvdandrieux** [mitmel/OpenLocast-Web#46]
A cast that's just been created, just been uploaded, is dated as "5h ago". 

All devices share the same timeclock, at the moments of creation of the cast (android), upload (android) and consultation (web).

**Comment by amarkbo** [comment]
This is an issue only in the front end, the API should output the correct time. I will fix the web front end to be consistent with the rest

**Comment by amarkbo** [comment]
Fixed in 6fe770ffb7a121d4a4245f9b0cd1f0c81f07eb7f
