### ISSUE TITLE
Cast date change 

### ISSUE THREAD

**Issue by mvdandrieux** [mitmel/OpenLocast-Web#49]
Sometimes, because of low battery or any other divine intervention, a cast has to be entered manually after the actual event. In that case, the geo tagging can happen via the drag and drop option, but the date time of the cast will remain irrelevant. If the cast was entered in the morning but talks about a night club, it will end up in a break fast query based on the date time Information

Possible to change the cast time front the front end ?

**Comment by amarkbo** [comment]
Casts have a datetime field in their model, however, it is currently only reflected in the admin site. Issue #51 opened.
