### ISSUE TITLE
Possibility to connect casts between themselves

### ISSUE THREAD

**Issue by mvdandrieux** [mitmel/OpenLocast-Web#54]
There would be a need for reflexive relations of the database between casts. For instance, an ethnological report could be a gathering of three casts happening one after the other on the same night.

Through the web interface, we could use a select box to connect one cast to another one on the same map, and a direct line could be the visual consequence of it.

**Comment by amarkbo** [comment]
I think this functionality can be supported through tagging or categories, rather than adding another mechanism for associating casts

**Comment by mvdandrieux** [comment]
What are categories ? If it's another system of tagging, then yes, we could use them both. But i haven't seen it in the back end.

**Comment by amarkbo** [comment]
Apologies, I meant "collections"

**Comment by mvdandrieux** [comment]
ho. Then maybe not. We will be using tags to quality the tags, and since its not possible to create collections on the fly via mobile, it's of no use here. The need it to connect several casts made on the same theme inside of a collection. In database terms, it would be a relation linking casts to another cast (just one), to give a sense of linearity.

Not a priority (at all).
