### ISSUE TITLE
API unreachable via jqXHR Object

### ISSUE THREAD

**Issue by mvdandrieux** [mitmel/OpenLocast-Web#57]
We attempted to read the API. I works perfectly through GET (http://mel-prod.media.mit.edu/eranos/api/cast/?author=3). But using the jqXHR Object, we get into one of the following situations: 
1. using json format reader : Origin http://test1.local is not allowed by Access-Control-Allow-Origin. (see http://stackoverflow.com/questions/10143093/origin-is-not-allowed-by-access-control-allow-origin)
2. using jsonp format reader : the &callback argument triggers an error on the API : http://mel-prod.media.mit.edu/eranos/api/cast/?author=3&callback=jQuery18203677591816522181_1364465737888&_=1364465737909

**Comment by xxv** [comment]
1. We can look into adding that header to the API responses.
2. That is because the callback querystring argument is being processed by our server, which is invalid. I'm not familiar with this particular technique: what is supposed to process the callback argument?

**Comment by mvdandrieux** [comment]
hi steve ! thank you for looking into this. The JSONP is a "padded" json format, where generally the padding is the function executed as a callback. From http://en.wikipedia.org/wiki/JSONP :

``` javascript
<script type="text/javascript"
        src="http://server2.example.com/Users/1234?jsonp=parseResponse">
</script>
```

In this example, the received payload would be:

``` javascript
parseResponse({"Name": "Foo", "Id": 1234, "Rank": 7});
```

But the locast API has not been designed this way. My guess is that the easiest was right now is to add the Access-Control-Allow-Origin headers to the API, and then add a control by token, for instance, to avoid data hijack.

**Comment by mvdandrieux** [comment]
@amarkb it sort of works now, but there's an encoding problem that i bumped into randomly, because of the "ë" caracter on my name. Try this : http://mel-prod.media.mit.edu/eranos/api/cast/?author=3&callback=jQuery1820725326772313565_1365411689168&_=1365411689185

**Comment by amarkbo** [comment]
This was due to some unicode issues in core related to how json was being served. Fixed.

**Comment by mvdandrieux** [comment]
Still not closed unfortunately. Origin http://test1.local is not allowed by Access-Control-Allow-Origin still prevents the content to be reached.

**Comment by amarkbo** [comment]
Fixed. Added (optional) CORS middleware in locast core https://github.com/mitmel/Locast-Web-Core/commit/8608a4fbbf7b601487229650bb845dbc15dd572c

**Comment by mvdandrieux** [comment]
So far the whole server is unaccessible, so can't really test...
