### ISSUE TITLE
Misplaced casts

### ISSUE THREAD

**Issue by mvdandrieux** [mitmel/OpenLocast-Web#61]
Some casts which have been uploaded via the app belonged to no collection at all. Is that even possible ? I've had to relink them from the back-end, in the collection panel.

Also they lost the geotagging data. Is it also even possible? That's really annoying because now the user will have to redrop them where they actually happened.

here are some exemples. They all come from the same user and the same phone (otherwise tested successfully for geotagging and posting with the Locast app)
- http://mel-prod.media.mit.edu/eranos/#!cast/51/
- http://mel-prod.media.mit.edu/eranos/#!cast/49/
- http://mel-prod.media.mit.edu/eranos/#!cast/46/
- http://mel-prod.media.mit.edu/eranos/#!cast/44/
- http://mel-prod.media.mit.edu/eranos/#!cast/18/
- http://mel-prod.media.mit.edu/eranos/#!cast/17/

**Comment by mvdandrieux** [comment]
More info about these Casts.
The geotag data is not lost it appears: when one clicks on them, they point at the right location. But they are displayed on the map at the wrong location.
![Screen Shot 2013-04-10 at 5 42 45 PM](https://f.cloud.github.com/assets/3766061/363008/8459636a-a1f6-11e2-8c20-24a1d9dff4d6.png)
![Screen Shot 2013-04-10 at 5 42 50 PM](https://f.cloud.github.com/assets/3766061/363009/8a9e7c06-a1f6-11e2-92f4-1da2cc60da8a.png)

**Comment by mvdandrieux** [comment]
if you've worked you magic, your magic worked... They're now where they belong.

**Comment by amarkbo** [comment]
I haven't changed anything! But glad it is working now... I'll keep an eye out.
